# Generated by Django 5.1.3 on 2025-02-23 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_photogra_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photographer_images/')),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
                ('utype', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='pixapp.tbl_photogra_register')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('photos_per_page', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo_ids', models.TextField(blank=True)),
                ('share_link', models.CharField(blank=True, max_length=255, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixapp.photofolder')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixapp.tbl_photogra_register')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='folder_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_image', models.ImageField(blank=True, null=True, upload_to='edited_photos/')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pixapp.photofolder')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_photos', to='pixapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_pages', models.IntegerField()),
                ('photos_per_page', models.JSONField()),
                ('page_titles', models.JSONField(blank=True, null=True)),
                ('page_descriptions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photos', models.ManyToManyField(related_name='client_albums', to='pixapp.photo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_albums', to='pixapp.tbl_register')),
            ],
        ),
    ]
