# Generated by Django 5.1.3 on 2025-02-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_photogra_register',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_register',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
