# Generated by Django 5.1.3 on 2025-02-23 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixapp', '0002_alter_tbl_photogra_register_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixapp.tbl_register')),
            ],
        ),
    ]
