# Generated by Django 5.1.3 on 2025-02-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixapp', '0003_clientphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('page_titles', models.JSONField(blank=True, null=True)),
                ('page_descriptions', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_albums', to='pixapp.tbl_register')),
                ('photos', models.ManyToManyField(related_name='custom_albums', to='pixapp.clientphoto')),
            ],
        ),
    ]
