# Generated by Django 5.1.3 on 2025-02-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixapp', '0004_customalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='customalbum',
            name='photos_per_page',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customalbum',
            name='total_pages',
            field=models.IntegerField(),
        ),
    ]
