# Generated by Django 5.1.3 on 2025-02-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixapp', '0005_customalbum_photos_per_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientphoto',
            name='edited_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_edited_photos/'),
        ),
        migrations.AddField(
            model_name='clientphoto',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientphoto',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
