# Generated by Django 5.1.3 on 2025-02-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixapp', '0006_clientphoto_edited_image_clientphoto_is_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientphoto',
            name='edited_image',
        ),
        migrations.RemoveField(
            model_name='clientphoto',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='clientphoto',
            name='order',
        ),
    ]
