# Generated by Django 5.1.3 on 2025-03-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixapp', '0007_remove_clientphoto_edited_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientphoto',
            name='edited_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos/edited/'),
        ),
        migrations.AddField(
            model_name='clientphoto',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientphoto',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
